const ROLES = {
  SEKRETARIS_KANTOR: "SEKRETARIS_KANTOR",
  KETUA_PENGURUS: "KETUA_PENGURUS",
  SEKRETARIS_PENGURUS: "SEKRETARIS_PENGURUS",
  BENDAHARA: "BENDAHARA",
  KEPALA_BAGIAN_PSDM: "KEPALA_BAGIAN_PSDM",
  KEPALA_BAGIAN_KEUANGAN: "KEPALA_BAGIAN_KEUANGAN",
  KEPALA_BAGIAN_UMUM: "KEPALA_BAGIAN_UMUM",
};

module.exports = {
  ROLES,
};
